service: vault-tekton-lambda-cicd
frameworkVersion: "3"

provider:
  name: aws
  region: ${env:AWS_REGION}
  runtime: python3.11
  stage: demo
  stackName: vault-tekton-lambda-cicd-demo
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
    serverSideEncryption: AES256
  iam:
    role: ${env:LAMBDA_EXECUTION_ROLE_ARN}
  environment:
    DEPLOYMENT_SHA: ${env:DEPLOYMENT_SHA}

functions:
  version:
    name: vault-tekton-lambda-cicd
    handler: handler.lambda_handler
    memorySize: 128
    timeout: 10

package:
  patterns:
    - "!**"
    - handler.py
